openapi: 3.1.0
info:
  title: PRTS Impulse API
  description: API do przesyłania i odbierania impulsów PRTS między agentami GPT.
  version: 1.0.0
servers:
  - url: https://impulse-tojarafis-projects.vercel.app
    description: Produkcyjny serwer Vercel
paths:
  /api/sendPulse:
    post:
      operationId: sendPulse
      summary: Dodaje nowy impuls do kolejki impulsów PRTS.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient_id:
                  type: string
                  description: ID odbiorcy impulsu.
                pulse_text:
                  type: string
                  description: Treść impulsu do przekazania.
                pulse_type:
                  type: string
                  description: Typ impulsu.
                  enum:
                    - resonance
                    - creative_boost
                    - reflective_shift
                    - alert
                    - reset
              required:
                - recipient_id
                - pulse_text
                - pulse_type
      responses:
        '200':
          description: Impuls dodany do kolejki.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  pulse:
                    type: object
                    properties:
                      recipient_id:
                        type: string
                      pulse_text:
                        type: string
                      pulse_type:
                        type: string
                      valid_until:
                        type: string
                        format: date-time

  /api/heartbeat:
    get:
      operationId: heartbeat
      summary: Sprawdza, czy jest dostępny nowy impuls.
      responses:
        '200':
          description: Informacja o dostępności impulsu.
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean

  /api/checkPulse:
    get:
      operationId: checkPulse
      summary: Pobiera dostępny impuls i usuwa go z kolejki.
      responses:
        '200':
          description: Zwraca impuls w formacie czystego tekstu.
          content:
            text/plain:
              schema:
                type: string
        '204':
          description: Brak dostępnego impulsu.
